### ISSUE TITLE
Typo in icon file name: emtpy.png vs empty.png

### ISSUE THREAD

**Issue by e28eta** [typefacts/alfred-special-characters#1]
I just installed your workflow (thanks!), and was poking through the contents. I noticed that the "emtpy.png" filename was misspelled, and wondered where it was being used.

It looks like characters.json has 67 references (one per character) to the correct spelling, which is a file that doesn't exist (as far as I can tell).

I don't know whether that means emtpy.png should just be deleted (and maybe the icon removed from each entry?), or whether it should be renamed so it's actually being used.

**Comment by normanposselt** [comment]
Hi,

we fixed that. Thank you.

–N.
