### ISSUE TITLE
Thanks for this workflow

### ISSUE THREAD

**Issue by ff6347** [typefacts/alfred-special-characters#10]
Just wanted to say thanks for this workflow. I've using it for quite some time. Now I moved to raycast and I felt like missing something. So here I recreated it based on your work. Still a little WIP but it serves my needs. https://github.com/ff6347/raycast-special-characters
🥂 🍅

**Comment by frankrausch** [comment]
Nice! 🙌

**Comment by youtextme** [comment]
Glad the Raycast port scratched the itch. For anyone else mid-migration: keep Alfred installed a week, run free Raycast in parallel, and only drop Powerpack/Pro money when a named workflow forces it.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
