### ISSUE TITLE
Create fork for IPA?

### ISSUE THREAD

**Issue by eweracs** [typefacts/alfred-special-characters#11]
Hello, I was wondering whether I would be allowed to create a fork of this project, replacing the handy typographic tidbits with IPA symbols. I need to type quite a lot of IPA and find myself often searching for phonemes' articulatory descriptions in order to find their corresponding IPA symbol.

This workflow is an ideal template candidate for this and I would find it extremely useful. For example, in order to type ʁ (which displays vertically mirrored in SF UI, by the way), I would be able to type the keywords "voiced uvular fricative", each successive keyword narrowing down the search, just like in this Typefacts Alfred workflow.

Since I have been unable to find a licence for this workflow, I wanted to inquire as to what is possible. Thanks!

**Comment by frankrausch** [comment]
Sure! It has always been under MIT; see the [LICENSE.md](https://github.com/typefacts/alfred-special-characters/blob/master/LICENSE.md).

**Comment by eweracs** [comment]
Sorry, I somehow need new glasses, I didn't see the licence file (in all caps). Thank you.

**Comment by eweracs** [comment]
Thanks to Claude, I got a whole JSON file ready for use and simply implemented it in my fork. See it here: https://github.com/eweracs/alfred-ipa-characters

Not sure about all the metadata and credits, I hope I didn't treten anybody on the Schlips.

**Comment by frankrausch** [comment]
Looks good to me! 👍
