### ISSUE TITLE
en and em dash

### ISSUE THREAD

**Issue by eweracs** [typefacts/alfred-special-characters#6]
Hi, the primary (only) reason I installed this was to be able to type en and em dashes in environments where they are not automatically substituted. I found them not to be included here, maybe they would make a good addition. Thank you!

**Comment by frankrausch** [comment]
Pro tip: Use ⌥ + `-` for en dash; use ⌥ + ⇧ + `-` for em dash.

But yes, for educational purposes, adding these characters to the Alfred workflow does make sense.

**Comment by eweracs** [comment]
Hi (again), the code I committed doesn't seem to be sufficient – I only edited the characters.json. If I try to type an endash with Alfred, it doesn't show up. Does the .alfredworfklow file need to change? Apologies for the hassle, I wish I knew how to fix this myself.

**Comment by frankrausch** [comment]
Oh yes: We usually update the .alfredworkflow for new releases.

So I’ve updated the .alfredworkflow and created v 1.1.8:
https://github.com/typefacts/alfred-special-characters/releases

**Comment by eweracs** [comment]
Wonderful, thank you very much!
